### ISSUE TITLE
Lack of actor in events

### ISSUE THREAD

**Issue by simon1222** [clarkwinkelmann/flarum-ext-author-change#10]
@clarkwinkelmann can you add actor to events?

**Comment by clarkwinkelmann** [comment]
Good call. I'll add this in a future update :+1:

**Comment by clarkwinkelmann** [comment]
After investigating, it seems like the actor was already properly added by Flarum, but the actor property wasn't explicitly documented in the event class.

I have released version 1.0.2 with proper documentation and type-hints.

Let me know if anything else might be missing, I'll investigate deeper!
