### ISSUE TITLE
Discussion / first post sync

### ISSUE THREAD

**Issue by clarkwinkelmann** [clarkwinkelmann/flarum-ext-author-change#4]
My plan to cover this would be as follows:

If the author AND date of the first post is the same as the discussion, offer a new checkbox that's enabled by default saying "Sync with discussion" or "Sync with first post".

If the author or date is different, show the checkbox disabled by default.

For posts that aren't number 1, don't show the checkbox at all.

When submitting with with the checkbox enabled, two requests are made, one to edit the post, the other to edit the discussion.

There shouldn't be any permission issue as the extension has a single permission that covers both post and discussion editing.

**Comment by iPurpl3x** [comment]
While you do that, could you also sync the `last_posted_at` field ? That would be really useful to have an impact on the default sorting of discussion that is based on that field.

**Comment by clarkwinkelmann** [comment]
Both implemented in 1.0.0
